package cpu

const (
	adcStr = "ADC"
	andStr = "AND"
	aslStr = "ASL"
	bccStr = "BCC"
	bcsStr = "BCS"
	beqStr = "BEQ"
	bitStr = "BIT"
	bmiStr = "BMI"
	bneStr = "BNE"
	bplStr = "BPL"
	brkStr = "BRK"
	bvcStr = "BVC"
	bvsStr = "BVS"
	clcStr = "CLC"
	cldStr = "CLD"
	cliStr = "CLI"
	clvStr = "CLV"
	cmpStr = "CMP"
	cpxStr = "CPX"
	cpyStr = "CPY"
	decStr = "DEC"
	dexStr = "DEX"
	deyStr = "DEY"
	eorStr = "EOR"
	incStr = "INC"
	inxStr = "INX"
	inyStr = "INY"
	jmpStr = "JMP"
	jsrStr = "JSR"
	ldaStr = "LDA"
	ldxStr = "LDX"
	ldyStr = "LDY"
	lsrStr = "LSR"
	nopStr = "NOP"
	oraStr = "ORA"
	phaStr = "PHA"
	phpStr = "PHP"
	plaStr = "PLA"
	plpStr = "PLP"
	rolStr = "ROL"
	rorStr = "ROR"
	rtiStr = "RTI"
	rtsStr = "RTS"
	sbcStr = "SBC"
	secStr = "SEC"
	sedStr = "SED"
	seiStr = "SEI"
	staStr = "STA"
	stxStr = "STX"
	styStr = "STY"
	taxStr = "TAX"
	tayStr = "TAY"
	tsxStr = "TSX"
	txaStr = "TXA"
	txsStr = "TXS"
	tyaStr = "TYA"
)

// createOpCodes returns the actual 6502 opcode definitions indexed by opcode.
func createOpCodes() [256]OpCodeDef {
	var opCodes [256]OpCodeDef
	id := NewInstruction(getAddressingMode)
	opCodes[0x69] = id.Instruction(Mnemonic(adcStr, ImmediateModeStr), 2, adc)
	opCodes[0x65] = id.Instruction(Mnemonic(adcStr, ZeropageModeStr), 3, adc)
	opCodes[0x75] = id.Instruction(Mnemonic(adcStr, ZeropageXModeStr), 4, adc)
	opCodes[0x6D] = id.Instruction(Mnemonic(adcStr, AbsoluteModeStr), 4, adc)
	opCodes[0x7D] = id.Instruction(Mnemonic(adcStr, AbsoluteIndexedXModeStr), 4, adc)
	opCodes[0x79] = id.Instruction(Mnemonic(adcStr, AbsoluteIndexedYModeStr), 4, adc)
	opCodes[0x61] = id.Instruction(Mnemonic(adcStr, IndexedIndirectModeStr), 6, adc)
	opCodes[0x71] = id.Instruction(Mnemonic(adcStr, IndirectIndexedModeStr), 5, adc)
	opCodes[0x29] = id.Instruction(Mnemonic(andStr, ImmediateModeStr), 2, and)
	opCodes[0x25] = id.Instruction(Mnemonic(andStr, ZeropageModeStr), 3, and)
	opCodes[0x35] = id.Instruction(Mnemonic(andStr, ZeropageXModeStr), 4, and)
	opCodes[0x2D] = id.Instruction(Mnemonic(andStr, AbsoluteModeStr), 4, and)
	opCodes[0x3D] = id.Instruction(Mnemonic(andStr, AbsoluteIndexedXModeStr), 4, and)
	opCodes[0x39] = id.Instruction(Mnemonic(andStr, AbsoluteIndexedYModeStr), 4, and)
	opCodes[0x21] = id.Instruction(Mnemonic(andStr, IndexedIndirectModeStr), 6, and)
	opCodes[0x31] = id.Instruction(Mnemonic(andStr, IndirectIndexedModeStr), 5, and)
	opCodes[0x0A] = id.Instruction(Mnemonic(aslStr, AccumulatorModeStr), 2, asl)
	opCodes[0x06] = id.Instruction(Mnemonic(aslStr, ZeropageModeStr), 5, asl)
	opCodes[0x16] = id.Instruction(Mnemonic(aslStr, ZeropageXModeStr), 6, asl)
	opCodes[0x0E] = id.Instruction(Mnemonic(aslStr, AbsoluteModeStr), 6, asl)
	opCodes[0x1E] = id.Instruction(Mnemonic(aslStr, AbsoluteIndexedXModeStr), 7, asl)
	opCodes[0x90] = id.Instruction(Mnemonic(bccStr, RelativeModeStr), 2, bcc)
	opCodes[0xB0] = id.Instruction(Mnemonic(bcsStr, RelativeModeStr), 2, bcs)
	opCodes[0xF0] = id.Instruction(Mnemonic(beqStr, RelativeModeStr), 2, beq)
	opCodes[0x24] = id.Instruction(Mnemonic(bitStr, ZeropageModeStr), 3, bit)
	opCodes[0x2C] = id.Instruction(Mnemonic(bitStr, AbsoluteModeStr), 4, bit)
	opCodes[0x30] = id.Instruction(Mnemonic(bmiStr, RelativeModeStr), 2, bmi)
	opCodes[0xD0] = id.Instruction(Mnemonic(bneStr, RelativeModeStr), 2, bne)
	opCodes[0x10] = id.Instruction(Mnemonic(bplStr, RelativeModeStr), 2, bpl)
	opCodes[0x00] = id.Instruction(Mnemonic(brkStr, ImpliedModeStr), 7, brk)
	opCodes[0x50] = id.Instruction(Mnemonic(bvcStr, RelativeModeStr), 2, bvc)
	opCodes[0x70] = id.Instruction(Mnemonic(bvsStr, RelativeModeStr), 2, bvs)
	opCodes[0x18] = id.Instruction(Mnemonic(clcStr, ImpliedModeStr), 2, clc)
	opCodes[0xD8] = id.Instruction(Mnemonic(cldStr, ImpliedModeStr), 2, cld)
	opCodes[0x58] = id.Instruction(Mnemonic(cliStr, ImpliedModeStr), 2, cli)
	opCodes[0xB8] = id.Instruction(Mnemonic(clvStr, ImpliedModeStr), 2, clv)
	opCodes[0xC9] = id.Instruction(Mnemonic(cmpStr, ImmediateModeStr), 2, cmp)
	opCodes[0xC5] = id.Instruction(Mnemonic(cmpStr, ZeropageModeStr), 3, cmp)
	opCodes[0xD5] = id.Instruction(Mnemonic(cmpStr, ZeropageXModeStr), 4, cmp)
	opCodes[0xCD] = id.Instruction(Mnemonic(cmpStr, AbsoluteModeStr), 4, cmp)
	opCodes[0xDD] = id.Instruction(Mnemonic(cmpStr, AbsoluteIndexedXModeStr), 4, cmp)
	opCodes[0xD9] = id.Instruction(Mnemonic(cmpStr, AbsoluteIndexedYModeStr), 4, cmp)
	opCodes[0xC1] = id.Instruction(Mnemonic(cmpStr, IndexedIndirectModeStr), 6, cmp)
	opCodes[0xD1] = id.Instruction(Mnemonic(cmpStr, IndirectIndexedModeStr), 5, cmp)
	opCodes[0xE0] = id.Instruction(Mnemonic(cpxStr, ImmediateModeStr), 2, cpx)
	opCodes[0xE4] = id.Instruction(Mnemonic(cpxStr, ZeropageModeStr), 3, cpx)
	opCodes[0xEC] = id.Instruction(Mnemonic(cpxStr, AbsoluteModeStr), 4, cpx)
	opCodes[0xC0] = id.Instruction(Mnemonic(cpyStr, ImmediateModeStr), 2, cpy)
	opCodes[0xC4] = id.Instruction(Mnemonic(cpyStr, ZeropageModeStr), 3, cpy)
	opCodes[0xCC] = id.Instruction(Mnemonic(cpyStr, AbsoluteModeStr), 4, cpy)
	opCodes[0xC6] = id.Instruction(Mnemonic(decStr, ZeropageModeStr), 5, dec)
	opCodes[0xD6] = id.Instruction(Mnemonic(decStr, ZeropageXModeStr), 6, dec)
	opCodes[0xCE] = id.Instruction(Mnemonic(decStr, AbsoluteModeStr), 6, dec)
	opCodes[0xDE] = id.Instruction(Mnemonic(decStr, AbsoluteIndexedXModeStr), 7, dec)
	opCodes[0xCA] = id.Instruction(Mnemonic(dexStr, ImpliedModeStr), 2, dex)
	opCodes[0x88] = id.Instruction(Mnemonic(deyStr, ImpliedModeStr), 2, dey)
	opCodes[0x49] = id.Instruction(Mnemonic(eorStr, ImmediateModeStr), 2, eor)
	opCodes[0x45] = id.Instruction(Mnemonic(eorStr, ZeropageModeStr), 3, eor)
	opCodes[0x55] = id.Instruction(Mnemonic(eorStr, ZeropageXModeStr), 4, eor)
	opCodes[0x4D] = id.Instruction(Mnemonic(eorStr, AbsoluteModeStr), 4, eor)
	opCodes[0x5D] = id.Instruction(Mnemonic(eorStr, AbsoluteIndexedXModeStr), 4, eor)
	opCodes[0x59] = id.Instruction(Mnemonic(eorStr, AbsoluteIndexedYModeStr), 4, eor)
	opCodes[0x41] = id.Instruction(Mnemonic(eorStr, IndexedIndirectModeStr), 6, eor)
	opCodes[0x51] = id.Instruction(Mnemonic(eorStr, IndirectIndexedModeStr), 5, eor)
	opCodes[0xE6] = id.Instruction(Mnemonic(incStr, ZeropageModeStr), 5, inc)
	opCodes[0xF6] = id.Instruction(Mnemonic(incStr, ZeropageXModeStr), 6, inc)
	opCodes[0xEE] = id.Instruction(Mnemonic(incStr, AbsoluteModeStr), 6, inc)
	opCodes[0xFE] = id.Instruction(Mnemonic(incStr, AbsoluteIndexedXModeStr), 7, inc)
	opCodes[0xE8] = id.Instruction(Mnemonic(inxStr, ImpliedModeStr), 2, inx)
	opCodes[0xC8] = id.Instruction(Mnemonic(inyStr, ImpliedModeStr), 2, iny)
	opCodes[0x4C] = id.Instruction(Mnemonic(jmpStr, AbsoluteModeStr), 3, jmp)
	opCodes[0x6C] = id.Instruction(Mnemonic(jmpStr, AbsoluteIndirectModeStr), 5, jmp)
	opCodes[0x20] = id.Instruction(Mnemonic(jsrStr, AbsoluteModeStr), 6, jsr)
	opCodes[0xA9] = id.Instruction(Mnemonic(ldaStr, ImmediateModeStr), 2, lda)
	opCodes[0xA5] = id.Instruction(Mnemonic(ldaStr, ZeropageModeStr), 3, lda)
	opCodes[0xB5] = id.Instruction(Mnemonic(ldaStr, ZeropageXModeStr), 4, lda)
	opCodes[0xAD] = id.Instruction(Mnemonic(ldaStr, AbsoluteModeStr), 4, lda)
	opCodes[0xBD] = id.Instruction(Mnemonic(ldaStr, AbsoluteIndexedXModeStr), 4, lda)
	opCodes[0xB9] = id.Instruction(Mnemonic(ldaStr, AbsoluteIndexedYModeStr), 4, lda)
	opCodes[0xA1] = id.Instruction(Mnemonic(ldaStr, IndexedIndirectModeStr), 6, lda)
	opCodes[0xB1] = id.Instruction(Mnemonic(ldaStr, IndirectIndexedModeStr), 5, lda)
	opCodes[0xA2] = id.Instruction(Mnemonic(ldxStr, ImmediateModeStr), 2, ldx)
	opCodes[0xA6] = id.Instruction(Mnemonic(ldxStr, ZeropageModeStr), 3, ldx)
	opCodes[0xB6] = id.Instruction(Mnemonic(ldxStr, ZeropageYModeStr), 4, ldx)
	opCodes[0xAE] = id.Instruction(Mnemonic(ldxStr, AbsoluteModeStr), 4, ldx)
	opCodes[0xBE] = id.Instruction(Mnemonic(ldxStr, AbsoluteIndexedYModeStr), 4, ldx)
	opCodes[0xA0] = id.Instruction(Mnemonic(ldyStr, ImmediateModeStr), 2, ldy)
	opCodes[0xA4] = id.Instruction(Mnemonic(ldyStr, ZeropageModeStr), 3, ldy)
	opCodes[0xB4] = id.Instruction(Mnemonic(ldyStr, ZeropageXModeStr), 4, ldy)
	opCodes[0xAC] = id.Instruction(Mnemonic(ldyStr, AbsoluteModeStr), 4, ldy)
	opCodes[0xBC] = id.Instruction(Mnemonic(ldyStr, AbsoluteIndexedXModeStr), 4, ldy)
	opCodes[0x4A] = id.Instruction(Mnemonic(lsrStr, AccumulatorModeStr), 2, lsr)
	opCodes[0x46] = id.Instruction(Mnemonic(lsrStr, ZeropageModeStr), 5, lsr)
	opCodes[0x56] = id.Instruction(Mnemonic(lsrStr, ZeropageXModeStr), 6, lsr)
	opCodes[0x4E] = id.Instruction(Mnemonic(lsrStr, AbsoluteModeStr), 6, lsr)
	opCodes[0x5E] = id.Instruction(Mnemonic(lsrStr, AbsoluteIndexedXModeStr), 7, lsr)
	opCodes[0xEA] = id.Instruction(Mnemonic(nopStr, ImpliedModeStr), 2, nop)
	opCodes[0x09] = id.Instruction(Mnemonic(oraStr, ImmediateModeStr), 2, ora)
	opCodes[0x05] = id.Instruction(Mnemonic(oraStr, ZeropageModeStr), 3, ora)
	opCodes[0x15] = id.Instruction(Mnemonic(oraStr, ZeropageXModeStr), 4, ora)
	opCodes[0x0D] = id.Instruction(Mnemonic(oraStr, AbsoluteModeStr), 4, ora)
	opCodes[0x1D] = id.Instruction(Mnemonic(oraStr, AbsoluteIndexedXModeStr), 4, ora)
	opCodes[0x19] = id.Instruction(Mnemonic(oraStr, AbsoluteIndexedYModeStr), 4, ora)
	opCodes[0x01] = id.Instruction(Mnemonic(oraStr, IndexedIndirectModeStr), 6, ora)
	opCodes[0x11] = id.Instruction(Mnemonic(oraStr, IndirectIndexedModeStr), 5, ora)
	opCodes[0x48] = id.Instruction(Mnemonic(phaStr, ImpliedModeStr), 3, pha)
	opCodes[0x68] = id.Instruction(Mnemonic(plaStr, ImpliedModeStr), 4, pla)
	opCodes[0x08] = id.Instruction(Mnemonic(phpStr, ImpliedModeStr), 3, php)
	opCodes[0x28] = id.Instruction(Mnemonic(plpStr, ImpliedModeStr), 4, plp)
	opCodes[0x2A] = id.Instruction(Mnemonic(rolStr, AccumulatorModeStr), 2, rol)
	opCodes[0x26] = id.Instruction(Mnemonic(rolStr, ZeropageModeStr), 5, rol)
	opCodes[0x36] = id.Instruction(Mnemonic(rolStr, ZeropageXModeStr), 6, rol)
	opCodes[0x2E] = id.Instruction(Mnemonic(rolStr, AbsoluteModeStr), 6, rol)
	opCodes[0x3E] = id.Instruction(Mnemonic(rolStr, AbsoluteIndexedXModeStr), 7, rol)
	opCodes[0x6A] = id.Instruction(Mnemonic(rorStr, AccumulatorModeStr), 2, ror)
	opCodes[0x66] = id.Instruction(Mnemonic(rorStr, ZeropageModeStr), 5, ror)
	opCodes[0x76] = id.Instruction(Mnemonic(rorStr, ZeropageXModeStr), 6, ror)
	opCodes[0x6E] = id.Instruction(Mnemonic(rorStr, AbsoluteModeStr), 6, ror)
	opCodes[0x7E] = id.Instruction(Mnemonic(rorStr, AbsoluteIndexedXModeStr), 7, ror)
	opCodes[0x40] = id.Instruction(Mnemonic(rtiStr, ImpliedModeStr), 6, rti)
	opCodes[0x60] = id.Instruction(Mnemonic(rtsStr, ImpliedModeStr), 6, rts)
	opCodes[0xE9] = id.Instruction(Mnemonic(sbcStr, ImmediateModeStr), 2, sbc)
	opCodes[0xE5] = id.Instruction(Mnemonic(sbcStr, ZeropageModeStr), 3, sbc)
	opCodes[0xF5] = id.Instruction(Mnemonic(sbcStr, ZeropageXModeStr), 4, sbc)
	opCodes[0xED] = id.Instruction(Mnemonic(sbcStr, AbsoluteModeStr), 4, sbc)
	opCodes[0xFD] = id.Instruction(Mnemonic(sbcStr, AbsoluteIndexedXModeStr), 4, sbc)
	opCodes[0xF9] = id.Instruction(Mnemonic(sbcStr, AbsoluteIndexedYModeStr), 4, sbc)
	opCodes[0xE1] = id.Instruction(Mnemonic(sbcStr, IndexedIndirectModeStr), 6, sbc)
	opCodes[0xF1] = id.Instruction(Mnemonic(sbcStr, IndirectIndexedModeStr), 5, sbc)
	opCodes[0x38] = id.Instruction(Mnemonic(secStr, ImpliedModeStr), 2, sec)
	opCodes[0xF8] = id.Instruction(Mnemonic(sedStr, ImpliedModeStr), 2, sed)
	opCodes[0x78] = id.Instruction(Mnemonic(seiStr, ImpliedModeStr), 2, sei)
	opCodes[0x85] = id.Instruction(Mnemonic(staStr, ZeropageModeStr), 3, sta)
	opCodes[0x95] = id.Instruction(Mnemonic(staStr, ZeropageXModeStr), 4, sta)
	opCodes[0x8D] = id.Instruction(Mnemonic(staStr, AbsoluteModeStr), 4, sta)
	opCodes[0x9D] = id.Instruction(Mnemonic(staStr, AbsoluteIndexedXModeStr), 5, sta)
	opCodes[0x99] = id.Instruction(Mnemonic(staStr, AbsoluteIndexedYModeStr), 5, sta)
	opCodes[0x81] = id.Instruction(Mnemonic(staStr, IndexedIndirectModeStr), 6, sta)
	opCodes[0x91] = id.Instruction(Mnemonic(staStr, IndirectIndexedModeStr), 6, sta)
	opCodes[0x86] = id.Instruction(Mnemonic(stxStr, ZeropageModeStr), 3, stx)
	opCodes[0x96] = id.Instruction(Mnemonic(stxStr, ZeropageYModeStr), 4, stx)
	opCodes[0x8E] = id.Instruction(Mnemonic(stxStr, AbsoluteModeStr), 4, stx)
	opCodes[0x84] = id.Instruction(Mnemonic(styStr, ZeropageModeStr), 3, sty)
	opCodes[0x94] = id.Instruction(Mnemonic(styStr, ZeropageXModeStr), 4, sty)
	opCodes[0x8C] = id.Instruction(Mnemonic(styStr, AbsoluteModeStr), 4, sty)
	opCodes[0xAA] = id.Instruction(Mnemonic(taxStr, ImpliedModeStr), 2, tax)
	opCodes[0xA8] = id.Instruction(Mnemonic(tayStr, ImpliedModeStr), 2, tay)
	opCodes[0xBA] = id.Instruction(Mnemonic(tsxStr, ImpliedModeStr), 2, tsx)
	opCodes[0x8A] = id.Instruction(Mnemonic(txaStr, ImpliedModeStr), 2, txa)
	opCodes[0x9A] = id.Instruction(Mnemonic(txsStr, ImpliedModeStr), 2, txs)
	opCodes[0x98] = id.Instruction(Mnemonic(tyaStr, ImpliedModeStr), 2, tya)
	return opCodes
}

func (p *CPU) addPCOffset(b byte) (uint16, bool) {
	pcLsb := uint16(p.Reg.PC & 0x00FF)
	offset := int8(b)
	pcLsb += uint16(offset)
	carryFlag := (pcLsb > uint16(0xFF))
	newPC := p.Reg.PC + uint16(offset)
	return newPC, carryFlag
}
